config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :friends
  resources :homes
  resources :messages
  get 'friends/index'
  root "homes#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user

  def rid
    if self.user_id < self.user_id_2
      x=self.user_id
      y=self.user_id_2
    else
      x=self.user_id_2
      y=self.user_id
    end
    (x*10)+y
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  belongs_to :friend
  has_many :messages
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
	before_action :configure_permitted_parameters, if: :devise_controller?

	protected

	def configure_permitted_parameters
	devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :age])
	end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
	def index
		user=User.find(current_user.id)
		@added_friends=Friend.where(user_id: user)
		@requested_friends=Friend.where(user_id_2: user)
	    @friends_email=@added_friends.pluck(:email)
		puts @friends_email.inspect
		puts @requested_friends.inspect
		puts "===================="
	end

	def new
		user=User.find(params[:add_friend])
		friend={
			name: user.name,
			age: user.age,
			email: user.email,
			user_id: current_user.id,
			user_id_2: user.id
		}
		@friend=Friend.new(friend)
		@friend.save
		room_id=@friend.rid
		room=Room.find_by(room_id: room_id)
		unless room.present?
			value={
				user_id: @friend.user_id,
				friend_id:@friend.id,
				room_id: room_id
			}
			room=Room.new(value)
			room.save
		end
		puts "=============================="
		puts room.inspect
		puts "=============================="
		redirect_to root_path
	end

	def destroy
		friend_1=Friend.find_by(params[:id])
		friend_2=Friend.find_by(user_id_2: friend_1.user_id)
		room_id=friend_1.rid
		room=Room.find_by(room_id: room_id)

		chat=Message.where(room_id: room.id)

		chat.destroy_all if chat.present?
		room.destroy if room.present?
		friend_2.destroy if friend_2.present?

		friend_1.destroy
		redirect_to friends_index_path(id: current_user.id)
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @users=User.where.not(id: current_user.id)
    friends=Friend.where(user_id: current_user)
    @friends_email=friends.pluck(:email)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def show
    @message=Message.new
    @friend=Friend.find(params[:id])
    @fid=params[:id]
    @room=Room.find_by(room_id:@friend.rid)
  end

  def new
    @message=Message.new
  end

  def create
    user= current_user
    @message=Message.new(messsage_params)
    @message.save!
    redirect_to messages_path(id:@fid)
  end

  private

  def messsage_params
    params.require(:message).permit(:content, :user_id, :room_id)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/friends/index.html.erb
<div class="card">
	<div class="card-title text-center mt-4 mb-4"><h1>FRIENDS</h1></div>
</div>

<% if @added_friends.length==0 and @requested_friends.length==0%>
	<div class="container">
		<h1>Add Some Friends</h1>
		<%= link_to "User Page" , root_path , class:"btn btn-secondary" %>
	</div>
<% else %>

	<div class="container">
		<table class="table mx-auto">
			<thead class="table table-dark border-1">
				<th>Name</th>
				<th>Age</th>
				<th colspan="4">Action</th>
			</thead>
			<tbody>
				<% @added_friends.each do |friend| %>
					<tr>
						<td><%= friend.name %></td>
						<td><%= friend.age %></td>
						<td><%= link_to 'Chat' , message_path(id: friend) , class:"btn btn-secondary"%></td>
						<td><%= link_to 'Unfriend', friends_path(friend) , method: :delete , data: {
							confirm: "Are you sure?"
						} , class:"btn btn-danger"%></td>
					</tr>
				<% end %>
				<% @requested_friends.each do |friend|  %>
					<% unless @friends_email.include?friend.user.email %>
						<tr>
							<td><%= friend.user.name %></td>
							<td><%= friend.user.age %></td>
							<td><%= link_to 'Chat' , messages_path(id: friend)%></td>
							<% if @friends_email.include?friend.user.email%>
								<td>ADDED</td>
							<% else %>
								<td><%= link_to 'Add' ,new_friend_path(:add_friend => friend.user_id)%></td>
							<% end %>
						</tr>
					<% end %>
				<% end %>
			</tbody>
		</table>	
	</div>
<% end %>

app/views/friends/new.html.erb
<h1>Friends#new</h1>
<p>Find me in app/views/friends/new.html.erb</p>

app/views/homes/index.html.erb
<div class="card border-0">
	<div class="card-title text-center mt-4 mb-4"><h1>USERS</h1></div>
</div>

<div class="container">
    <table class="table table-hover">
    <thead class="table-danger">
        <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Age</th>
        <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>
        <% @users.each_with_index do |user,i|%>
            <% if current_user.email !=user.email%>
            <tr>
                <td scope="row"><%=i+1%></td>
                <td><%=user.name%></td>
                <td><%=user.age%></td>
                <% if @friends_email.include?user.email%>
                    <td>ADDED</td>
                <% else %>
                    <td><%= link_to 'Add' ,new_friend_path(:add_friend => user) , class:"btn btn-primary"%></td>
                <% end %>
            </tr>
            <%end%>
        <%end%>
    </tbody>
    </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
  </head>

  <body>
    <%=render "shared/header"%>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/messages/new.html.erb
<h1>Messages#new</h1>
<p>Find me in app/views/messages/new.html.erb</p>

app/views/messages/show.html.erb
<div class="card">
	<div class="card-title text-center"><h1>
		<% unless @friend.name == current_user.name%>
			<%= @friend.name %> 
		<% else %>
			<%= @friend.user.name %>
		<% end %>
		</h1>
	</div>	
</div>

<div class="card mx-5 mt-5 w-50 h-25 mx-auto">
	<div class="card-body border-1 scroll">
		<% @room.messages.each do |message|%>
			<div class="mt-2 mx-5">
				<% if message.user == current_user%>
					<div class="float-end bg-success rounded-2 w-25 text-center"><%= message.content%>
					</div>
					<br>
					<div class="fs-6 fw-light float-sm-end">you</div>
					<br>
				<%else%>
					<div class="bg-info rounded-2 w-25 text-center"><%= message.content%>
					</div>
					<p class="fs-6 fw-light"><%= message.user.name%></p>
				<% end %>
			</div>
		<% end %>
	</div>

	<%= form_with(model: @message) do |f|%>
		<div class="d-flex">
			<%= f.hidden_field :user_id ,value: current_user.id %>
			<%= f.hidden_field :room_id ,value: @room.id %>
			<%= f.text_field :content, placeholder: "Write your message..." ,class:"form-control w-75 border-2 border-dark rounded-0" %>
			<%= f.submit "SEND" ,class:"btn btn-primary w-25 rounded-0" %>
		</div>
	<% end %>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%=link_to "Home", homes_path, class: "navbar-brand active" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%=link_to "Friends", friends_path, class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Sign Out', destroy_user_session_path, data: {turbo_method: :delete},class: "nav-link"%>
        </li>
        <%else%>
          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path, class: "nav-link"%>
          </li>
        </li>
        <%end%>
       
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>